### PR TITLE
Passed all 50 tests*

### PR DESCRIPTION
**Pull request by jaredcraig**
*Some proxy tests fail when not ran in certain order, however, all tests did pass.

### CODE REVIEW

**Comment by kennygman** [comment]
Awesome! The proxy things are most likely a server error. We talked with
the tas. Jared, can you email the project to the tas?

**Comment by jaredcraig** [comment]
Just zip the whole student dir and e-mail?

**Comment by kennygman** [comment]
Yep! You may have to attach via google drive if its too big.

**Comment by jaredcraig** [comment]
Ok, will do.
Here's last test from last push/pull request:

jared@jared-Inspiron-7520:~/git/dreamteamcatan/student_01_03_15$ ant test
Buildfile: /home/jared/git/dreamteamcatan/student_01_03_15/build.xml

init:
    [mkdir] Created dir: /home/jared/git/dreamteamcatan/student_01_03_15/java/build
    [mkdir] Created dir: /home/jared/git/dreamteamcatan/student_01_03_15/java/dist

compile:
    [javac] Compiling 190 source files to /home/jared/git/dreamteamcatan/student_01_03_15/java/build

test:
     [java] JUnit version 4.11
     [java] ..................................................
     [java] Time: 52.731
     [java] 
     [java] OK (50 tests)
     [java] 

BUILD SUCCESSFUL
Total time: 56 seconds
jared@jared-Inspiron-7520:~/git/dreamteamcatan/student_01_03_15$

**Comment by kennygman** [comment]
You are the man!

**Pull request merged**
